steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/processjr-docs:$COMMIT_SHA'
      - '-f'
      - 'documentation/Dockerfile'
      - 'documentation'
images:
  - 'gcr.io/$PROJECT_ID/processjr-docs:$COMMIT_SHA'
