services:
  # --- PROCESSJR OPERATIONAL DOCS ---
  processjr-docs:
    build:
      context: ./documentation
      dockerfile: Dockerfile
    container_name: processjr-docs
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./documentation:/docs
